spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meli-orders
    username: ${DB_USER:postgres}
    password: david123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update